name: DevSync Daily Repository Update

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "30 9 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Activity Log for 23f1002114@ds.study.iitm.ac.in
        run: |
          mkdir -p logs
          # Update activity log with current timestamp
          echo "$(date '+%Y-%m-%d %H:%M:%S UTC') - Daily automated update executed" >> logs/activity.log
          echo "Workflow run ID: ${{ github.run_id }}" >> logs/activity.log
          echo "Triggered by: DevSync Daily Automation" >> logs/activity.log
          echo "---" >> logs/activity.log

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "DevSync Daily Update - $(date '+%Y-%m-%d %H:%M:%S UTC')" || exit 0
          git push